name:           sketchgrid
version:        0.0.0
author:         Herman Bergwerf <hermanbergwerf@gmail.com>
description:    Sketcher for technical illustrations.
homepage:       https://github.com/hermanbergwerf/sketchgrid
environment:
  sdk:          '>=1.8.0 <2.0.0'
dependencies:
  htgen:        ^0.0.1
  tuple:        ^1.0.1
  euclid:       ^0.0.3
  collection:   ^1.14.0
  vector_math:  ^2.0.4
dev_dependencies:
  sass:         ^0.4.2+7
  browser:      ^0.10.0+2

transformers:
- sass
